name: Dependency Scan

on:
  push:
    branches: [start]
  pull_request:

jobs:
  depcheck-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Project
        run: mvn -B clean package -DskipTests

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "bankapp"
          path: "."
          format: "HTML"
          args: >
            --failOnCVSS 7
            --nvdApiKey ${{ secrets.NVD_API_KEY }}

      - name: Upload Dependency Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports